version: '3.1'
services:
  # postgres:
  #   image: postgres
  #   restart: always
  #   volumes:
  #     - ./docker-data/db-data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   ports:
  #     - 5432:5432

  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker-data/db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}
      
  maildev:
    image: maildev/maildev
    ports:
      - "1080:80"

  adminer:
    depends_on:
      - mysql
      - maildev
      # - postgres
    image: adminer
    restart: always
    ports:
      - 8080:8080